name: Terraform CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      action:
        description: 'Terraform action to perform'
        required: true
        default: 'plan'
        type: choice
        options:
        - plan
        - apply
        - destroy

env:
  TF_VERSION: '1.0.0'
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT }}

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: ${{ env.TF_VERSION }}

    - name: Authenticate to Google Cloud
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

    - name: Setup Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ env.GCP_PROJECT_ID }}

    - name: Terraform Init
      run: terraform init

    - name: Terraform Format
      run: terraform fmt -check

    - name: Terraform Plan
      if: github.event.inputs.action == 'plan' || github.event_name == 'pull_request'
      run: terraform plan -out=tfplan

    - name: Terraform Apply
      if: github.event.inputs.action == 'apply' && github.event_name == 'workflow_dispatch'
      run: |
        terraform apply -auto-approve tfplan
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add terraform.tfstate
        git commit -m "Update Terraform state" || echo "No changes to commit"
        git push

    - name: Terraform Destroy
      if: github.event.inputs.action == 'destroy' && github.event_name == 'workflow_dispatch'
      run: |
        terraform destroy -auto-approve
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add terraform.tfstate
        git commit -m "Update Terraform state after destroy" || echo "No changes to commit"
        git push

    - name: Upload Terraform Plan
      if: github.event.inputs.action == 'plan' || github.event_name == 'pull_request'
      uses: actions/upload-artifact@v2
      with:
        name: tfplan
        path: tfplan