name: Terraform CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      action:
        description: 'Terraform action to perform'
        required: true
        default: 'plan'
        type: choice
        options:
        - plan
        - apply
        - destroy
      module:
        description: 'Terraform module to target'
        required: true
        default: 'all'
        type: choice
        options:
        - gke-cluster
        - another-module
        - all

env:
  TF_VERSION: '1.3.9'
  TF_CLOUD_ORGANIZATION: "mypro"
  TF_WORKSPACE: "gcp"
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    env:
      TF_TOKEN_app_terraform_io: ${{ secrets.TF_API_TOKEN }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: ${{ env.TF_VERSION }}
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    - name: Authenticate to Google Cloud
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

    - name: Setup Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ env.GCP_PROJECT_ID }}

    - name: Terraform Format
      run: terraform fmt -check

    - name: Terraform Init
      run: terraform init
      env:
        TF_VAR_credentials: ${{ secrets.GCP_CREDENTIALS }}

    - name: Terraform Plan
      if: (github.event.inputs.action == 'plan' || github.event_name == 'pull_request') && github.event.inputs.module == 'gke-cluster'
      run: terraform plan -target=module.gke_cluster
      env:
        TF_VAR_credentials: ${{ secrets.GCP_CREDENTIALS }}

    - name: Terraform Plan (Another Module)
      if: (github.event.inputs.action == 'plan' || github.event_name == 'pull_request') && github.event.inputs.module == 'another-module'
      run: terraform plan -target=module.another_module
      env:
        TF_VAR_credentials: ${{ secrets.GCP_CREDENTIALS }}

    - name: Terraform Apply
      if: github.event.inputs.action == 'apply' && github.event_name == 'workflow_dispatch' && github.event.inputs.module == 'gke-cluster'
      run: terraform apply -target=module.gke_cluster -auto-approve
      env:
        TF_VAR_credentials: ${{ secrets.GCP_CREDENTIALS }}

    - name: Terraform Apply (Another Module)
      if: github.event.inputs.action == 'apply' && github.event_name == 'workflow_dispatch' && github.event.inputs.module == 'another-module'
      run: terraform apply -target=module.another_module -auto-approve
      env:
        TF_VAR_credentials: ${{ secrets.GCP_CREDENTIALS }}

    - name: Terraform Destroy
      if: github.event.inputs.action == 'destroy' && github.event_name == 'workflow_dispatch' && github.event.inputs.module == 'gke-cluster'
      run: terraform destroy -target=module.gke_cluster -auto-approve
      env:
        TF_VAR_credentials: ${{ secrets.GCP_CREDENTIALS }}

    - name: Terraform Destroy (Another Module)
      if: github.event.inputs.action == 'destroy' && github.event_name == 'workflow_dispatch' && github.event.inputs.module == 'another-module'
      run: terraform destroy -target=module.another_module -auto-approve
      env:
        TF_VAR_credentials: ${{ secrets.GCP_CREDENTIALS }}

    - name: Terraform Plan (All Modules)
      if: (github.event.inputs.action == 'plan' || github.event_name == 'pull_request') && github.event.inputs.module == 'all'
      run: terraform plan
      env:
        TF_VAR_credentials: ${{ secrets.GCP_CREDENTIALS }}

    - name: Terraform Apply (All Modules)
      if: github.event.inputs.action == 'apply' && github.event_name == 'workflow_dispatch' && github.event.inputs.module == 'all'
      run: terraform apply -auto-approve
      env:
        TF_VAR_credentials: ${{ secrets.GCP_CREDENTIALS }}

    - name: Terraform Destroy (All Modules)
      if: github.event.inputs.action == 'destroy' && github.event_name == 'workflow_dispatch' && github.event.inputs.module == 'all'
      run: terraform destroy -auto-approve
      env:
        TF_VAR_credentials: ${{ secrets.GCP_CREDENTIALS }}
